// SPDX-License-Identifier: MPL-2.0
//
// Pure source-comment scanner and encoder. The scanner deliberately accepts
// only comments whose delimiter is the first token after indentation. This
// avoids treating ordinary code and most string literals as comments while
// remaining useful across languages without embedding a full parser.

export type SourceCommentKind = 'header' | 'line' | 'block' | 'docblock';

export interface SourceCommentRecord {
    /** Inclusive, 0-based first source line. */
    readonly startLine: number;
    /** Inclusive, 0-based last source line. */
    readonly endLine: number;
    /** Comment decorations removed; logical lines are joined with `\n`. */
    readonly text: string;
    readonly kind: SourceCommentKind;
    /**
     * Safe annotation-id fragment carried by comments generated by OOCI.
     * The marker is removed from `text` so a generated comment can round-trip
     * without creating an annotation whose message starts with `OOCI(...)`.
     */
    readonly annotationIdFragment?: string;
}

export type SourceCommentEncodingStyle = 'auto' | 'line' | 'block' | 'docblock';

export interface EncodeSourceCommentOptions {
    /** Stable annotation id. Only a safe, short fragment is emitted. */
    readonly annotationId: string;
    /** Spaces/tabs to place before every generated comment line. */
    readonly indentation?: string;
    /** `auto` prefers a line comment and otherwise uses a block. */
    readonly style?: SourceCommentEncodingStyle;
}

interface LineCommentStyle {
    readonly prefix: string;
    readonly kind: 'line' | 'docblock';
}

interface BlockCommentStyle {
    readonly open: string;
    readonly close: string;
    readonly kind: 'block' | 'docblock';
    /** Conventional leading `*` on each body line. */
    readonly starBody?: boolean;
    /** Additional body sequences forbidden by the language grammar. */
    readonly forbiddenBodySequences?: readonly string[];
}

interface LanguageCommentSyntax {
    readonly lines: readonly LineCommentStyle[];
    readonly blocks: readonly BlockCommentStyle[];
    /** Sequences unsafe even inside line comments (notably PHP's closing tag). */
    readonly forbiddenMessageSequences?: readonly string[];
}

const C_LINE_STYLES: readonly LineCommentStyle[] = [
    { prefix: '///', kind: 'docblock' },
    { prefix: '//!', kind: 'docblock' },
    { prefix: '//', kind: 'line' },
];

const C_BLOCK_STYLES: readonly BlockCommentStyle[] = [
    { open: '/**', close: '*/', kind: 'docblock', starBody: true },
    { open: '/*', close: '*/', kind: 'block', starBody: true },
];

const C_FAMILY: LanguageCommentSyntax = {
    lines: C_LINE_STYLES,
    blocks: C_BLOCK_STYLES,
};

const HASH_FAMILY: LanguageCommentSyntax = {
    lines: [{ prefix: '#', kind: 'line' }],
    blocks: [],
};

const SQL_FAMILY: LanguageCommentSyntax = {
    lines: [{ prefix: '--', kind: 'line' }],
    blocks: C_BLOCK_STYLES,
};

const LUA_FAMILY: LanguageCommentSyntax = {
    lines: [{ prefix: '--', kind: 'line' }],
    blocks: [{ open: '--[[', close: ']]', kind: 'block' }],
};

const HASKELL_FAMILY: LanguageCommentSyntax = {
    lines: [{ prefix: '--', kind: 'line' }],
    blocks: [{ open: '{-', close: '-}', kind: 'block' }],
};

const MARKUP_FAMILY: LanguageCommentSyntax = {
    lines: [],
    blocks: [{ open: '<!--', close: '-->', kind: 'block', forbiddenBodySequences: ['--'] }],
};

const CSS_FAMILY: LanguageCommentSyntax = {
    lines: [],
    blocks: C_BLOCK_STYLES,
};

const SCSS_FAMILY: LanguageCommentSyntax = {
    lines: C_LINE_STYLES,
    blocks: C_BLOCK_STYLES,
};

const POWERSHELL_FAMILY: LanguageCommentSyntax = {
    lines: [{ prefix: '#', kind: 'line' }],
    blocks: [{ open: '<#', close: '#>', kind: 'block' }],
};

const SEMICOLON_FAMILY: LanguageCommentSyntax = {
    lines: [
        { prefix: ';;;', kind: 'line' },
        { prefix: ';;', kind: 'line' },
        { prefix: ';', kind: 'line' },
    ],
    blocks: [{ open: '#|', close: '|#', kind: 'block' }],
};

const CLOJURE_FAMILY: LanguageCommentSyntax = {
    lines: SEMICOLON_FAMILY.lines,
    blocks: [],
};

const INI_FAMILY: LanguageCommentSyntax = {
    lines: [
        { prefix: ';', kind: 'line' },
        { prefix: '#', kind: 'line' },
    ],
    blocks: [],
};

const PHP_FAMILY: LanguageCommentSyntax = {
    lines: [...C_LINE_STYLES, { prefix: '#', kind: 'line' }],
    blocks: C_BLOCK_STYLES,
    forbiddenMessageSequences: ['?>'],
};

const VUE_FAMILY: LanguageCommentSyntax = {
    lines: C_LINE_STYLES,
    blocks: [...MARKUP_FAMILY.blocks, ...C_BLOCK_STYLES],
};

const LANGUAGE_SYNTAX: Readonly<Record<string, LanguageCommentSyntax>> = {
    typescript: C_FAMILY,
    typescriptreact: C_FAMILY,
    javascript: C_FAMILY,
    javascriptreact: C_FAMILY,
    java: C_FAMILY,
    c: C_FAMILY,
    cpp: C_FAMILY,
    csharp: C_FAMILY,
    go: C_FAMILY,
    rust: C_FAMILY,
    swift: C_FAMILY,
    kotlin: C_FAMILY,
    dart: C_FAMILY,
    php: PHP_FAMILY,

    python: HASH_FAMILY,
    ruby: HASH_FAMILY,
    shellscript: HASH_FAMILY,
    shell: HASH_FAMILY,
    bash: HASH_FAMILY,
    zsh: HASH_FAMILY,
    powershell: POWERSHELL_FAMILY,
    perl: HASH_FAMILY,
    r: HASH_FAMILY,
    yaml: HASH_FAMILY,
    toml: HASH_FAMILY,
    dockerfile: HASH_FAMILY,
    makefile: HASH_FAMILY,

    sql: SQL_FAMILY,
    lua: LUA_FAMILY,
    haskell: HASKELL_FAMILY,

    html: MARKUP_FAMILY,
    xml: MARKUP_FAMILY,
    svg: MARKUP_FAMILY,
    markdown: MARKUP_FAMILY,
    vue: VUE_FAMILY,
    css: CSS_FAMILY,
    scss: SCSS_FAMILY,

    clojure: CLOJURE_FAMILY,
    clojurescript: CLOJURE_FAMILY,
    lisp: SEMICOLON_FAMILY,
    scheme: SEMICOLON_FAMILY,
    ini: INI_FAMILY,
};

function syntaxFor(languageId: string): LanguageCommentSyntax | undefined {
    return LANGUAGE_SYNTAX[languageId.trim().toLocaleLowerCase('en-US')];
}

/** Whether the codec has an explicit, non-fallback syntax for `languageId`. */
export function supportsSourceCommentLanguage(languageId: string): boolean {
    return syntaxFor(languageId) !== undefined;
}

const AMBIGUOUS_MIXED_CONTEXT_LANGUAGES = new Set(['typescriptreact', 'javascriptreact', 'vue', 'php']);

/**
 * Whether one comment syntax is safe at every source position in this
 * language mode. Mixed template/code modes still support scanning, but need
 * a syntax-aware parser before annotations can be written safely.
 */
export function supportsSourceCommentEncoding(languageId: string): boolean {
    const normalized = languageId.trim().toLocaleLowerCase('en-US');
    return syntaxFor(normalized) !== undefined && !AMBIGUOUS_MIXED_CONTEXT_LANGUAGES.has(normalized);
}

function sourceLines(source: string | readonly string[]): string[] {
    const lines = typeof source === 'string' ? source.split('\n') : [...source];
    return lines.map((line, index) => {
        let normalized = line.endsWith('\r') ? line.slice(0, -1) : line;
        if (index === 0 && normalized.startsWith('\uFEFF')) {
            normalized = normalized.slice(1);
        }
        return normalized;
    });
}

function removeOneLeadingSpace(value: string): string {
    const first = value[0];
    return first === ' ' || first === '\t' ? value.slice(1).trimEnd() : value.trimEnd();
}

function trimEmptyEdges(lines: string[]): string[] {
    let start = 0;
    let end = lines.length;
    while (start < end && lines[start].trim().length === 0) {
        start++;
    }
    while (end > start && lines[end - 1].trim().length === 0) {
        end--;
    }
    return lines.slice(start, end);
}

function cleanBlockText(fragments: readonly string[], style: BlockCommentStyle): string {
    const cleaned = fragments.map((fragment) => {
        let line = fragment.trim();
        if (style.starBody && line.startsWith('*')) {
            line = removeOneLeadingSpace(line.slice(1));
        }
        return line.trimEnd();
    });
    return trimEmptyEdges(cleaned).join('\n');
}

interface ParsedGeneratedMarker {
    readonly text: string;
    readonly annotationIdFragment?: string;
}

const GENERATED_ANNOTATION_MARKER = /^OOCI\(([A-Za-z0-9_-]{1,8})\)(?:[ \t]+|$)/;

function parseGeneratedAnnotationMarker(value: string): ParsedGeneratedMarker {
    const lines = value.split('\n');
    const match = GENERATED_ANNOTATION_MARKER.exec(lines[0] ?? '');
    if (!match) {
        return { text: value };
    }
    lines[0] = (lines[0] ?? '').slice(match[0].length);
    return {
        text: trimEmptyEdges(lines).join('\n'),
        annotationIdFragment: match[1],
    };
}

interface ScannedBlock {
    readonly endLine: number;
    readonly text: string;
    readonly hasTrailingCode: boolean;
}

function scanBlock(lines: readonly string[], startLine: number, style: BlockCommentStyle): ScannedBlock {
    const fragments: string[] = [];
    let lineIndex = startLine;
    let content = lines[startLine].trimStart().slice(style.open.length);

    while (lineIndex < lines.length) {
        const closeIndex = content.indexOf(style.close);
        if (closeIndex !== -1) {
            fragments.push(content.slice(0, closeIndex));
            return {
                endLine: lineIndex,
                text: cleanBlockText(fragments, style),
                hasTrailingCode: content.slice(closeIndex + style.close.length).trim().length > 0,
            };
        }

        fragments.push(content);
        lineIndex++;
        if (lineIndex < lines.length) {
            content = lines[lineIndex].trim();
        }
    }

    return {
        endLine: Math.max(startLine, lines.length - 1),
        text: cleanBlockText(fragments, style),
        hasTrailingCode: false,
    };
}

function matchingBlock(trimmedLine: string, syntax: LanguageCommentSyntax): BlockCommentStyle | undefined {
    return syntax.blocks.find((style) => trimmedLine.startsWith(style.open));
}

function matchingLine(trimmedLine: string, syntax: LanguageCommentSyntax): LineCommentStyle | undefined {
    return syntax.lines.find((style) => trimmedLine.startsWith(style.prefix));
}

function isPreambleDirective(trimmedLine: string, line: number, languageId: string): boolean {
    if (line === 0 && trimmedLine.startsWith('#!')) {
        return true;
    }
    if ((languageId === 'xml' || languageId === 'svg') && trimmedLine.startsWith('<?xml')) {
        return true;
    }
    if ((languageId === 'html' || languageId === 'markdown') && /^<!doctype\s/i.test(trimmedLine)) {
        return true;
    }
    if (languageId === 'php' && trimmedLine === '<?php') {
        return true;
    }
    return languageId === 'css' && trimmedLine.startsWith('@charset ');
}

function markdownFenceDelimiter(trimmedLine: string): string | undefined {
    if (trimmedLine.startsWith('```')) {
        return '```';
    }
    if (trimmedLine.startsWith('~~~')) {
        return '~~~';
    }
    return undefined;
}

/**
 * Scan standalone source comments. Inline comments (`code // comment`) are
 * intentionally ignored. Consecutive line comments are returned as one
 * record, and every comment before the first code token is a file header.
 */
export function scanSourceComments(source: string | readonly string[], languageId: string): SourceCommentRecord[] {
    const normalizedLanguageId = languageId.trim().toLocaleLowerCase('en-US');
    const syntax = syntaxFor(normalizedLanguageId);
    if (!syntax) {
        return [];
    }

    const lines = sourceLines(source);
    const records: SourceCommentRecord[] = [];
    let lineIndex = 0;
    let inHeader = true;
    let markdownFence: string | undefined;

    while (lineIndex < lines.length) {
        const trimmed = lines[lineIndex].trimStart();
        if (trimmed.length === 0) {
            lineIndex++;
            continue;
        }

        if (normalizedLanguageId === 'markdown') {
            const delimiter = markdownFenceDelimiter(trimmed);
            if (delimiter) {
                if (!markdownFence) {
                    markdownFence = delimiter;
                    inHeader = false;
                } else if (delimiter === markdownFence) {
                    markdownFence = undefined;
                }
                lineIndex++;
                continue;
            }
            if (markdownFence) {
                lineIndex++;
                continue;
            }
        }

        if (inHeader && isPreambleDirective(trimmed, lineIndex, normalizedLanguageId)) {
            lineIndex++;
            continue;
        }

        const blockStyle = matchingBlock(trimmed, syntax);
        if (blockStyle) {
            const block = scanBlock(lines, lineIndex, blockStyle);
            const parsed = parseGeneratedAnnotationMarker(block.text);
            if (parsed.text.length > 0 || parsed.annotationIdFragment) {
                records.push({
                    startLine: lineIndex,
                    endLine: block.endLine,
                    text: parsed.text,
                    kind: inHeader ? 'header' : blockStyle.kind,
                    ...(parsed.annotationIdFragment ? { annotationIdFragment: parsed.annotationIdFragment } : {}),
                });
            }
            if (block.hasTrailingCode) {
                inHeader = false;
            }
            lineIndex = block.endLine + 1;
            continue;
        }

        const lineStyle = matchingLine(trimmed, syntax);
        if (lineStyle) {
            const startLine = lineIndex;
            const textLines: string[] = [];
            while (lineIndex < lines.length) {
                const candidate = lines[lineIndex].trimStart();
                const candidateStyle = matchingLine(candidate, syntax);
                if (!candidateStyle || candidateStyle.prefix !== lineStyle.prefix) {
                    break;
                }
                textLines.push(removeOneLeadingSpace(candidate.slice(lineStyle.prefix.length)));
                lineIndex++;
            }
            const parsed = parseGeneratedAnnotationMarker(trimEmptyEdges(textLines).join('\n'));
            if (parsed.text.length > 0 || parsed.annotationIdFragment) {
                records.push({
                    startLine,
                    endLine: lineIndex - 1,
                    text: parsed.text,
                    kind: inHeader ? 'header' : lineStyle.kind,
                    ...(parsed.annotationIdFragment ? { annotationIdFragment: parsed.annotationIdFragment } : {}),
                });
            }
            continue;
        }

        inHeader = false;
        lineIndex++;
    }

    return records;
}

function sanitizeMessage(message: string): string {
    const normalized = message.split('\r\n').join('\n').split('\r').join('\n');
    let safe = '';
    for (const character of normalized) {
        const codePoint = character.codePointAt(0) ?? 0;
        if (codePoint === 10 || codePoint === 9) {
            safe += character;
        } else if ((codePoint >= 0 && codePoint < 32) || (codePoint >= 127 && codePoint <= 159)) {
            safe += ' ';
        } else if (codePoint === 0x2028 || codePoint === 0x2029) {
            safe += '\n';
        } else {
            safe += character;
        }
    }
    return safe.trim();
}

export function sourceCommentAnnotationIdFragment(annotationId: string): string {
    let compact = '';
    for (const character of annotationId.trim()) {
        const codePoint = character.codePointAt(0) ?? 0;
        const isDigit = codePoint >= 48 && codePoint <= 57;
        const isUppercase = codePoint >= 65 && codePoint <= 90;
        const isLowercase = codePoint >= 97 && codePoint <= 122;
        if (isDigit || isUppercase || isLowercase || character === '_' || character === '-') {
            compact += character;
        }
        if (compact.length === 8) {
            break;
        }
    }
    return compact || 'unknown';
}

/** Marker embedded in generated source comments for idempotent round trips. */
export function sourceCommentAnnotationMarker(annotationId: string): string {
    return `OOCI(${sourceCommentAnnotationIdFragment(annotationId)})`;
}

function safeIndentation(indentation: string | undefined): string {
    let safe = '';
    for (const character of indentation ?? '') {
        if (character !== ' ' && character !== '\t') {
            break;
        }
        safe += character;
    }
    return safe;
}

function breakSequence(value: string, sequence: string): string {
    if (sequence.length < 2) {
        return value.split(sequence).join(' ');
    }
    const replacement = `${sequence.slice(0, -1)} ${sequence.slice(-1)}`;
    return value.split(sequence).join(replacement);
}

function neutralizeSequences(value: string, sequences: readonly string[]): string {
    return sequences.reduce((result, sequence) => breakSequence(result, sequence), value);
}

function encodeLineComment(
    message: string,
    marker: string,
    indentation: string,
    style: LineCommentStyle,
    syntax: LanguageCommentSyntax
): string {
    const safeMessage = neutralizeSequences(message, syntax.forbiddenMessageSequences ?? []);
    const logicalLines = safeMessage.length > 0 ? safeMessage.split('\n') : [''];
    return logicalLines
        .map((line, index) => {
            const content = index === 0 ? `${marker}${line.length > 0 ? ` ${line}` : ''}` : line;
            return `${indentation}${style.prefix}${content.length > 0 ? ` ${content}` : ''}`.trimEnd();
        })
        .join('\n');
}

function encodeBlockComment(
    message: string,
    marker: string,
    indentation: string,
    style: BlockCommentStyle,
    syntax: LanguageCommentSyntax
): string {
    const unsafeSequences = [
        style.open,
        style.close,
        ...(style.forbiddenBodySequences ?? []),
        ...(syntax.forbiddenMessageSequences ?? []),
    ];
    const safeMessage = neutralizeSequences(message, unsafeSequences);
    const logicalLines = safeMessage.length > 0 ? safeMessage.split('\n') : [''];
    const body = logicalLines.map((line, index) => {
        const content = index === 0 ? `${marker}${line.length > 0 ? ` ${line}` : ''}` : line;
        const decoration = style.starBody ? ' *' : ' ';
        return `${indentation}${decoration}${content.length > 0 ? ` ${content}` : ''}`.trimEnd();
    });
    const close = style.starBody ? `${indentation} ${style.close}` : `${indentation}${style.close}`;
    return [`${indentation}${style.open}`, ...body, close].join('\n');
}

/**
 * Encode an annotation message as a syntactically valid standalone source
 * comment. Terminators and control characters are neutralized so message/id
 * content cannot break out of the generated comment.
 */
export function encodeSourceComment(message: string, languageId: string, options: EncodeSourceCommentOptions): string {
    const syntax = syntaxFor(languageId);
    if (!syntax) {
        throw new Error(`Unsupported source-comment languageId: ${languageId}`);
    }
    if (!supportsSourceCommentEncoding(languageId)) {
        throw new Error(`Language ${languageId} requires mixed-language context to encode comments safely`);
    }

    const style = options.style ?? 'auto';
    const indentation = safeIndentation(options.indentation);
    const marker = sourceCommentAnnotationMarker(options.annotationId);
    const safeMessage = sanitizeMessage(message);

    if (style === 'line' || (style === 'auto' && syntax.lines.length > 0)) {
        const lineStyle = syntax.lines.find((candidate) => candidate.kind === 'line') ?? syntax.lines[0];
        if (!lineStyle) {
            throw new Error(`Language ${languageId} does not support line comments`);
        }
        return encodeLineComment(safeMessage, marker, indentation, lineStyle, syntax);
    }

    const requestedBlockKind = style === 'docblock' ? 'docblock' : 'block';
    const blockStyle = syntax.blocks.find((candidate) => candidate.kind === requestedBlockKind);
    if (!blockStyle) {
        throw new Error(`Language ${languageId} does not support ${requestedBlockKind} comments`);
    }
    return encodeBlockComment(safeMessage, marker, indentation, blockStyle, syntax);
}
